<?php
$lang['terms_terms'] = 'conditions générales d\'utilisation';
$lang['terms_row1'] = 'ceci représente les conditions générales d\'utilisations du site web Machinedz.com. Veuillez réspecter notre politique d\'utilisation.';
$lang['terms_row2title'] = "Rôle de Machinedz.com";
$lang['terms_row2'] = "le rôle de Machinedz.com est de proposer les annonces publiées par les annonceurs afin de faciliter la tâche pour trouver ce que les visiteurs cherchent.<br />Tout type de contact entre l'annonceur et le visiteur du site web n'est pas prise en compte par notre équipe. Machinedz.com n'est pas responsable des act d'achat, location ou vente entre les annonceurs et visiteurs du site web.";
$lang['terms_row3title'] = "Déposer des annonces gratuitement";
$lang['terms_row3'] = "Machinedz.com vous propose de publier des annonces gratuitement et cela par ouvrir un compte gratuit. Les comptes gratuits sont limité par le nombre d'annonces publiées.<br />L'ouvertur d'un compte sur Machinedz.com requis des informations tel l'adresse email, numéro de téléphone, toutes ces informations ne seront utilisées que pour permettre aux visiteurs de contacter celui qui a publier l'annonce.<br />Afin de publier des annonces, il faut activer le compte par email après l'inscription sur Machinedz.com, notre équipe se réserve le droit de supprimer tout compte qui ne sera pas activé après 48 Heures de son ouverture.";
$lang['terms_row4title'] = "suppression des annonces";
$lang['terms_row4'] = "Notre équipe se réserve le droit de supprimer toute annonce qui ne respecte pas la mise en fome établie par le système de publication de Machinedz.com.";
$lang['terms_row5title'] = "blocage et suppression des comptes gratuits";
$lang['terms_row5'] = "Notre équipe se réserve le droit de supprimer ou bloquer tout compte utilisé pour publier des annonces qui ne repecte pas la mise en forme établie par le système de publication de Machinedz.com, ou des annonces qui avec des descriptions contenant des mots vulgaires ou a caractère érotique.";
$lang['terms_row6title'] = "Commande de parc de véhicules";
$lang['terms_row6'] = "Si vous êtes un professionnel, vous pouvez disposer d'une présentation propre à votre entreprise, améliorer la visibilté de vos annonces et regrouper toutes vos annonces dans un seul lieu. <br />Pour commader un parc de véhicules vous devez choisir une option de visiblité.<br/>Chaque option de visibilité a son propre tarif mensuel. Notre équipe se réserve le droit de changer les tarifs mensuel d'une ou de toutes les options de visibilité.<br />Le paiement des tarifs sont par CCP, lorsque vous commander un parc de véhicules un agent de notre équipe commercial vas vous contacter dans les meilleurs délais afin de finaliser la procédure d'ouverture de votre parc de véhicules.<br /> Toute commande non confirmée par le client sera supprimée par Notre équipe.";
$lang['terms_row7title'] = "Expiration des comptes professionnels";
$lang['terms_row7'] = "Si vous êtes un professionnel et que vous avez un parc de véhicules sur Machinedz.com, vous serez averti par email quelques jour avant l'expiration de votre parc de véhicules. Si vous ne confirmez pas le renouvelement de votre parc de véhicules, notre équipe se réserve le droit de bloquer ou supprimer votre compte.";